name: 'NYC Coverage Validator'
description: 'Validates code coverage percentage'
inputs:
  threshold-pct:  # id of input
    default: 80
outputs:
  status:  # id of input
   default: true
runs:
  using: 'node16'
  main: 'index.js'