name: 'NYC Coverage Validator'
description: 'Validates code coverage percentage'
inputs:
  threshold-pct:
    description: 'threshold percentage'
    required: true
  path:
    description: 'coverage folder path'
    required: true
    default: ${{ github.workspace }}
outputs:
  status:
    description: 'output the status of coverage'
runs:
  using: 'node16'
  main: 'index.js'
